apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gameapp-frontend
  template:
    metadata:
      labels:
        app: gameapp-frontend
    spec:
      containers:
        - name: frontend
          image: manojkrishnappa/gameappfrontend:3695a5d371a7737cba7564c568f80d914480e4a0
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi